Create country.js
Leref/aoi.js-library pull request #1
Opened 2023-07-18 20:31 UTC by JollyJolli

2023-07-19 17:42 UTC, Leref commented
Please copy the structure similar to https://github.com/Leref/aoi.js-library/blob/main/src/plugins/default/comment.js

the methods such `name, type, author, etc`.

As well putting the files you've created under your name, it will be same for author method.

2023-07-19 23:32 UTC, JollyJolli reviewed
👍

2023-07-20 02:20 UTC, Leref requested changes

2023-07-20 02:20 UTC, Leref commented on src/plugins/jollyjolli/country.js
> +  type: "djs",
Add missing metadata

2023-07-20 02:22 UTC, Leref commented on src/plugins/jollyjolli/country.js
> +// $country[country;format]
Also not needed :)

2023-07-20 02:28 UTC, Leref approved these changes

2023-07-20 02:28 UTC, merged