$tesseract function
Leref/aoi.js-library pull request #9
Opened 2023-08-11 21:00 UTC by Faf4a

Ability to read text of images, check code for example

2023-08-11 21:41 UTC, Leref requested changes

2023-08-11 21:41 UTC, Leref commented on plugins/fafa/tesseract/index.js
> +const advancedSplitText = require('./tesseract')
tesseract *

2023-08-11 21:43 UTC, Faf4a commented on plugins/fafa/tesseract/index.js
> +const advancedSplitText = require('./tesseract')
fixed

2023-08-12 00:27 UTC, Leref approved these changes

2023-08-12 00:27 UTC, merged